local _, BD = ...

BD.DEFAULTS = {
    enabled = true,
    minDamage = 0,
    abbreviate = true,
    showSpellIcon = false,
    fontSize = 14,
    duration = 1.0,
    floatDistance = 20,
    hideBlizzardFCT = true,
    onlyMyDamage = true,
    allNameplates = false,
    includePetDamage = true,
    debug = false,
    numberStyle = "retail",
    useSchoolColors = false,
    locale = "auto",
    layoutRevision = 4,
}

BD.STYLE_PRESETS = {
    retail = {
        fontFlags = "OUTLINE",
        fontScale = 1.0,
        popScale = 1.06,
        popDuration = 0.12,
        fadeMode = "smooth",
        fadePower = 1.35,
        fadeInRatio = 0.12,
        driftX = 0,
        useSchoolColors = false,
        defaultColor = { 1.0, 0.93, 0.0 },
        critColor = { 1.0, 0.93, 0.0 },
        critPopStartScale = 0.72,
        critRestScale = 1.18,
        critSlapScale = 1.42,
        critSlapDuration = 0.18,
        critSlapDrop = 0,
        durationMult = 1.0,
        floatMult = 1.85,
        critDurationMult = 1.1,
        animMode = "retailPop",
        critsHold = false,
        floatEase = "outCubic",
        spawnBaseY = -26,
        spawnLanes = {
            { 0, 0 },
            { 0, 14 },
            { 16, 6 },
            { -16, 6 },
            { 0, 26 },
            { 22, 18 },
            { -22, 18 },
        },
        spawnMinDist = 22,
        spawnMinDistCrit = 28,
        spawnJitter = 12,
        shadowOffset = { 1, -1 },
    },
    classic = {
        fontFlags = "THICKOUTLINE",
        fontScale = 1.0,
        popScale = 1.0,
        popDuration = 0,
        fadeMode = "inExpo",
        fadeInRatio = 0.3,
        driftX = 0,
        useSchoolColors = false,
        defaultColor = { 1.0, 0.93, 0.0 },
        critColor = { 1.0, 0.93, 0.0 },
        animMode = "classicPow",
        critsHold = true,
        critRestScale = 2.0,
        critPowStartScale = 1.0,
        critPowPeakScale = 4.0,
        critPowDuration = 0.2,
        durationMult = 1.0,
        floatMult = 1.0,
        critDurationMult = 1.6,
        floatEase = "outQuad",
        spawnBaseY = 20,
        spawnCritY = -8,
        spawnLanes = {
            { 0, 0 },
            { 18, 0 },
            { -18, 0 },
            { 0, 16 },
            { 16, 14 },
            { -16, 14 },
            { 0, 28 },
            { 10, 8 },
            { -10, 8 },
        },
        spawnMinDist = 20,
        spawnMinDistCrit = 26,
        spawnJitter = 10,
        shadowOffset = { 2, -2 },
    },
}

BD.BLIZZ_FCT_CVARS = {
    "enableFloatingCombatText",
    "floatingCombatTextCombatDamage_v2",
    "floatingCombatTextCombatDamageAllAutos_v2",
    "floatingCombatTextCombatHealing_v2",
    "floatingCombatTextCombatHealingAbsorbSelf_v2",
    "floatingCombatTextCombatHealingAbsorbTarget_v2",
    "floatingCombatTextCombatLogPeriodicSpells_v2",
    "floatingCombatTextPetMeleeDamage_v2",
    "floatingCombatTextPetSpellDamage_v2",
    "floatingCombatTextDodgeParryMiss_v2",
    "floatingCombatTextDamageReduction_v2",
    "floatingCombatTextAuras_v2",
    "floatingCombatTextAuraFade_v2",
    "floatingCombatTextHonorGains_v2",
    "floatingCombatTextEnergyGains_v2",
    "floatingCombatTextPeriodicEnergyGains_v2",
    "floatingCombatTextReactives_v2",
    "floatingCombatTextFriendlyHealers_v2",
    "floatingCombatTextComboPoints_v2",
    "floatingCombatTextLowManaHealth_v2",
    "floatingCombatTextRepChanges_v2",
    "floatingCombatTextCombatState_v2",
    "floatingCombatTextFloatMode_v2",
    "floatingCombatTextCombatDamageDirectionalScale_v2",
    "floatingCombatTextCombatDamage",
    "floatingCombatTextCombatHealing",
    "floatingCombatTextCombatLogPeriodicSpells",
    "floatingCombatTextPetMeleeDamage",
    "floatingCombatTextPetSpellDamage",
}

BD.MISS_ACTIONS = {
    BLOCK = true,
    DODGE = true,
    PARRY = true,
    MISS = true,
    IMMUNE = true,
    DEFLECT = true,
    REFLECT = true,
    RESIST = true,
    ABSORB = true,
    EVADE = true,
}

BD.DAMAGE_SCHOOL_COLORS = {
    [1] = { 1.0, 0.93, 0.0 },
    [2] = { 1.0, 0.90, 0.50 },
    [4] = { 1.0, 0.50, 0.0 },
    [8] = { 0.30, 1.0, 0.30 },
    [16] = { 0.50, 1.0, 1.0 },
    [32] = { 0.50, 0.50, 1.0 },
    [64] = { 1.0, 0.50, 1.0 },
}

BD.OUTGOING_ATTRIBUTION_WINDOW = 1.25
BD.AUTO_ATTACK_FALLBACK_GAP = 0.9
BD.AUTO_ATTACK_SPELL_ID = 6603
BD.POOL_SIZE = 24
BD.METER_PROBE_MAX_SPELLS = 6
